// =============================================================
//  LEIDING & FOERIERS
// =============================================================

export const leiding = [
  {
    naam: 'Nina',
    rol: 'Leiding',
    foto: 'https://primary.jwwb.nl/public/p/f/j/temp-ahwblxnkyvbftejiwqoa/nina-high.jpg?enable-io=true&enable=upscale&crop=1%3A1&width=800',
    totem: 'Liliumwitte modeste perdix',
    studie: 'Interieurarchitectuur',
    hobbys: '',
    weetje: '',
    figuur: '',
  },
  {
    naam: 'Marie',
    rol: 'Leiding',
    foto: 'https://primary.jwwb.nl/public/p/f/j/temp-ahwblxnkyvbftejiwqoa/marie-dc-high.jpg?enable-io=true&enable=upscale&crop=1%3A1&width=800',
    totem: 'Cosmeaoranje chaleureuse zebra',
    studie: 'Vroedkunde',
    hobbys: '',
    weetje: '',
    figuur: '',
  },
  {
    naam: 'Lise',
    rol: 'Leiding',
    foto: 'https://primary.jwwb.nl/public/p/f/j/temp-ahwblxnkyvbftejiwqoa/lise-l-high.jpg?enable-io=true&enable=upscale&crop=1%3A1&width=800',
    totem: 'Parrotia persicagele integere secretarisvogel',
    studie: 'Productontwikkeling',
    hobbys: '',
    weetje: '',
    figuur: '',
  },
  {
    naam: 'Jade',
    rol: 'Leiding',
    foto: 'https://primary.jwwb.nl/public/p/f/j/temp-ahwblxnkyvbftejiwqoa/jade-high.jpg?enable-io=true&enable=upscale&crop=1%3A1&width=800',
    totem: 'Goerami blauwe goedhartige karaca',
    studie: 'Lerarenopleiding lager onderwijs',
    hobbys: '',
    weetje: '',
    figuur: '',
  },
  {
    naam: 'Daan',
    rol: 'Leiding',
    foto: 'https://primary.jwwb.nl/public/p/f/j/temp-ahwblxnkyvbftejiwqoa/daan-high.jpg?enable-io=true&enable=upscale&crop=1%3A1&width=800',
    totem: 'Tamarin oranje joviale wapiti',
    studie: 'Educatief secundaire leerkracht',
    hobbys: '',
    weetje: '',
    figuur: '',
  },
  {
    naam: 'Hannelore',
    rol: 'Leiding',
    foto: 'https://primary.jwwb.nl/public/p/f/j/temp-ahwblxnkyvbftejiwqoa/hannelore-high.jpg?enable-io=true&enable=upscale&crop=1%3A1&width=800',
    totem: 'Zonnevlamgele glunderende Mapache',
    studie: 'Biomedische laboratoriumtechnologie',
    hobbys: '',
    weetje: '',
    figuur: '',
  },
  {
    naam: 'Witse',
    rol: 'leiding',
    foto: 'https://primary.jwwb.nl/public/p/f/j/temp-ahwblxnkyvbftejiwqoa/witse-high.jpg?enable-io=true&enable=upscale&crop=1%3A1&width=800',
    totem: 'Coleusgroene Welberaden Lijster',
    studie: 'IT',
    hobbys: '',
    weetje: '',
    figuur: '',
  },
]

export const foeriers = [
  {
    naam: 'Rune',
    rol: 'Foerier',
    foto: 'https://primary.jwwb.nl/public/p/f/j/temp-ahwblxnkyvbftejiwqoa/rune-high.jpg?enable-io=true&enable=upscale&crop=1%3A1&width=800',
    totem: 'Phulsumagroene toegewijde steenloper',
    studie: 'Revalidatiewetenschappen en kinesitherapie',
    hobbys: '',
    weetje: '',
    figuur: '',
  },
  {
    naam: 'Diaz',
    rol: 'Foerier',
    foto: 'https://primary.jwwb.nl/public/p/f/j/temp-ahwblxnkyvbftejiwqoa/diaz-high.jpg?enable-io=true&enable=upscale&crop=1%3A1&width=800',
    totem: 'Alkyoni-blauwe coulante zeezwaluw',
    studie: 'Pedagogische wetenschappen',
    hobbys: '',
    weetje: '',
    figuur: '',
  },
  {
    naam: 'Ella',
    rol: 'Foerier',
    foto: 'ella.jpeg',
    totem: 'Blijhartige Lumba Lumba',
    studie: '',
    hobbys: '',
    weetje: '',
    figuur: '',
  },
  {
    naam: 'Louise',
    rol: 'Foerier',
    foto: 'louise.jpeg',
    totem: 'Miraculeuze Syngnathida',
    studie: '',
    hobbys: '',
    weetje: '',
    figuur: '',
  },
]

export const foeriersIntro =
  'Zonder onze foeriers geen lekker eten en geen draaiend kamp. Ook zij stellen zich graag even voor!'
